# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.0
group=io.github.magishanpixel.mgn_witch_hat
java_version=21

# Common
minecraft_version=1.21.1
mod_name=MGN's Witch Hat
mod_author=MagishanPixel
mod_id=mgn_witch_hat
license=MagishanPixel's License (check repo)
credits=
description=Adds cosmetic hats
minecraft_version_range=[1.21.1, 1.22)

neo_form_version=1.21.1-20240808.144430

parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.116.12+1.21.1
fabric_loader_version=0.19.3

# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.233
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Depend
balm_version=21.0.56+1.21.1
balm_version_min=21.0.56

